# Generated by Django 3.2.7 on 2021-10-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirtmodel',
            name='shirt_gender',
        ),
        migrations.AddField(
            model_name='shirtmodel',
            name='gender',
            field=models.CharField(default='M', max_length=10, verbose_name='Gender (M or F)'),
        ),
        migrations.AddField(
            model_name='shirtmodel',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='shirtmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
