# Generated by Django 3.2.7 on 2021-11-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_shirtmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtmodel',
            name='img',
            field=models.FileField(null=True, upload_to='shirt-models/', verbose_name='Picture'),
        ),
    ]
