# Generated by Django 3.2.7 on 2021-11-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_rename_prodcuts_prodcut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcut',
            new_name='Product',
        ),
    ]
