# Generated by Django 3.2.7 on 2021-11-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_prodcut_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SideBarElement',
            new_name='SuitSideBarElement',
        ),
    ]
