# Generated by Django 3.2.7 on 2021-11-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_rename_sidebarelement_suitsidebarelement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShirtModel',
            new_name='SuitProduct',
        ),
    ]
