# Generated by Django 3.2.7 on 2021-11-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_rename_shirtmodel_suitproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitproduct',
            name='gender',
        ),
    ]
