# Generated by Django 3.2.7 on 2021-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_remove_suitproduct_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitproduct',
            name='img',
            field=models.FileField(null=True, upload_to='suit-products/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='suitsidebarelement',
            name='img',
            field=models.FileField(null=True, upload_to='suit-sidebar-elements/', verbose_name='Picture'),
        ),
    ]
