# Generated by Django 3.2.7 on 2021-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_suitjacketbuttoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitjacketbuttoning',
            name='prod',
            field=models.FileField(null=True, upload_to='suit-products/', verbose_name='Product'),
        ),
    ]
