# Generated by Django 3.2.7 on 2021-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_suitjacketbuttoning_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='suit-products/', verbose_name='Picture')),
            ],
        ),
        migrations.DeleteModel(
            name='SuitJacketButtoning',
        ),
    ]
