# Generated by Django 3.2.7 on 2021-11-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20211116_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SuitJacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SuitShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SuitTrouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='ThreePieceSuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Tuxedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='TwoPieceSuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
                ('fabric', models.CharField(choices=[('test', 'test')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Waistcoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='products/', verbose_name='Picture')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
