# Generated by Django 3.2.7 on 2021-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20211116_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='twopiecesuit',
            name='button_hole_thread',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True, verbose_name='Button Hole Threads'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='buttoning',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='buttons',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='contrasts',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='lapel',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='lining',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='pockets',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='trouser_back_pocket',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True, verbose_name='Trouser Back Pocket'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='trouser_buttoning',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True, verbose_name='Trouser Buttoning'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='trouser_pockets',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True, verbose_name='Trouser Pockets'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='trouser_turn_up',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True, verbose_name='Trouser Turn Up'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='vent',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='fabric',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
    ]
