# Generated by Django 3.2.7 on 2021-11-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20211117_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='buttoning',
            field=models.CharField(choices=[('test', 'test')], max_length=100, null=True),
        ),
    ]
