# Generated by Django 3.2.7 on 2021-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_alter_twopiecesuit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='twopiecesuit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=20),
        ),
    ]
