# Generated by Django 3.2.7 on 2021-11-17 16:36

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_twopiecesuit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='img',
            field=models.FileField(null=True, upload_to=index.models.upload_image_path, verbose_name='Picture'),
        ),
    ]
