# Generated by Django 3.2.7 on 2021-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_alter_twopiecesuit_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
