# Generated by Django 3.2.7 on 2021-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_alter_twopiecesuit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='fabric',
            field=models.CharField(choices=[('test asdoiu wqodj', 'test asdoiu wqodj')], max_length=100, null=True),
        ),
    ]
