# Generated by Django 3.2.7 on 2021-11-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_alter_twopiecesuit_fabric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuitSideBarElement',
            new_name='TwoPieceSuitSideBarElement',
        ),
    ]
