# Generated by Django 3.2.7 on 2021-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_rename_suitsidebarelement_twopiecesuitsidebarelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrastNeckFelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='contrast-neck-felts/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='LapelStitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='lapel-stitches/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='PocketFlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='pocket-flaps/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SleeveButtonThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='sleeve-button-threads/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SleeveContrastButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='sleeve-contrast-buttons/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Stitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='stitching/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='ticket-pockets/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='TrouserBackPocketDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='trouser-back-pocket-designs/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='TrouserBackPocketPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='trouser-back-pocket-placements/', verbose_name='Picture')),
            ],
        ),
        migrations.DeleteModel(
            name='Contrast',
        ),
        migrations.DeleteModel(
            name='Pocket',
        ),
        migrations.DeleteModel(
            name='TrouserBackPocket',
        ),
        migrations.RemoveField(
            model_name='twopiecesuit',
            name='contrasts',
        ),
        migrations.RemoveField(
            model_name='twopiecesuit',
            name='pockets',
        ),
        migrations.RemoveField(
            model_name='twopiecesuit',
            name='trouser_back_pocket',
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='contrast_neck_felt',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Contrast Neck Felt'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='lapel_stitch',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Lapel Sticth'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='pocket_flap',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Pocket Flap'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='sleeve_button_thread',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Sleeve Button Thread'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='sleeve_contrast_buttons',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Sleeve Contrast Buttons'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='stitching',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='ticket_pocket',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Ticket Pocket'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='trouser_back_pocket_design',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Trouser Back Pocket Design'),
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='trouser_back_pocket_placement',
            field=models.CharField(choices=[], max_length=100, null=True, verbose_name='Trouser Back Pocket Placement'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='button_hole_thread',
            field=models.CharField(choices=[('match fabric', 'Match fabric'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True, verbose_name='Button Hole Threads'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='buttoning',
            field=models.CharField(choices=[('one-button', 'One-button'), ('two-button', 'Two-button'), ('double-breasted', 'Double-breasted')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='buttons',
            field=models.CharField(choices=[('denver, black', 'Denver, black'), ('ridge, navy', 'Ridge, navy'), ('reggio, brown', 'Reggio, brown'), ('golden', 'Golden')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='fabric',
            field=models.CharField(choices=[('havanna, black', 'Havanna, black'), ('stockholm, brown', 'Stockholm, brown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='lining',
            field=models.CharField(choices=[('default', 'Default'), ('ardington, golden dark brown', 'Ardington, golden dark brown'), ('ardington, steel blue', 'Ardington, steel blue')], max_length=100, null=True),
        ),
    ]
