# Generated by Django 3.2.7 on 2021-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20211124_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeckFeltContrast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='neck-felt-contrasts/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SleeveButtonContrast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='sleeve-buttons-contrasts/', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='StitchingThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='stitching-threads/', verbose_name='Picture')),
            ],
        ),
        migrations.DeleteModel(
            name='ContrastNeckFelt',
        ),
        migrations.DeleteModel(
            name='SleeveContrastButton',
        ),
        migrations.DeleteModel(
            name='Stitching',
        ),
        migrations.RenameField(
            model_name='twopiecesuit',
            old_name='contrast_neck_felt',
            new_name='neck_felt_contrast',
        ),
        migrations.RenameField(
            model_name='twopiecesuit',
            old_name='sleeve_contrast_buttons',
            new_name='sleeve_buttons_contrast',
        ),
        migrations.RenameField(
            model_name='twopiecesuit',
            old_name='stitching',
            new_name='stitching_thread',
        ),
    ]
