# Generated by Django 3.2.7 on 2021-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_auto_20211124_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twopiecesuit',
            name='sleeve_button_thread',
        ),
        migrations.AddField(
            model_name='twopiecesuit',
            name='sleeve_buttons_thread',
            field=models.CharField(choices=[('no sleeve button thread', 'No sleeve button thread'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True, verbose_name='Sleeve Buttons Thread'),
        ),
        migrations.AlterField(
            model_name='sleevebuttonthread',
            name='img',
            field=models.FileField(null=True, upload_to='sleeve-buttons-threads/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='buttons',
            field=models.CharField(choices=[('denver, black', 'Denver, black'), ('ridge, navy', 'Ridge, navy'), ('reggio, brown', 'Reggio, brown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='lapel',
            field=models.CharField(choices=[('standard lapel', 'Standard lapel'), ('slim lapel', 'Slim lapel'), ('peak lapel', 'Peak lapel'), ('shawl lapel', 'Shawl lapel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='lapel_stitch',
            field=models.CharField(choices=[("don't stitch", "Don't stitch"), ('stitch lapel', 'Stitch lapel')], max_length=100, null=True, verbose_name='Lapel Sticth'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='lining',
            field=models.CharField(choices=[('default lining', 'Default lining'), ('ardington, golden dark brown', 'Ardington, golden dark brown'), ('ardington, steel blue', 'Ardington, steel blue')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='neck_felt_contrast',
            field=models.CharField(choices=[('skye, black', 'Skye, black'), ('skye, brown', 'Skye, brown'), ('skye, electric blue', 'Skye, electric blue')], max_length=100, null=True, verbose_name='Neck Felt Contrast'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='pocket_flap',
            field=models.CharField(choices=[('make flap', 'Make flap'), ("don't make flap", "Don't make flap")], max_length=100, null=True, verbose_name='Pocket Flap'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='sleeve_buttons_contrast',
            field=models.CharField(choices=[('no sleeve button contrast', 'No sleeve button contrast'), ('denver, black', 'Denver, black'), ('ridge, navy', 'Ridge, navy'), ('reggio, brown', 'Reggio, brown')], max_length=100, null=True, verbose_name='Sleeve Buttons Contrast'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='stitching_thread',
            field=models.CharField(choices=[('no stitching thread', 'No stitching thread'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='ticket_pocket',
            field=models.CharField(choices=[('put ticket pocket', 'Put ticket pocket'), ("don't put ticket pocket", "Don't put ticket pocket")], max_length=100, null=True, verbose_name='Ticket Pocket'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='trouser_back_pocket_design',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('buttoned', 'Buttoned')], max_length=100, null=True, verbose_name='Trouser Back Pocket Design'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='trouser_back_pocket_placement',
            field=models.CharField(choices=[("don't place it", "Don't place it"), ('right', 'Right'), ('both', 'Both')], max_length=100, null=True, verbose_name='Trouser Back Pocket Placement'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='trouser_buttoning',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible')], max_length=100, null=True, verbose_name='Trouser Buttoning'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='trouser_pockets',
            field=models.CharField(choices=[('straight', 'Straight'), ('beveled', 'Beveled')], max_length=100, null=True, verbose_name='Trouser Pockets'),
        ),
        migrations.AlterField(
            model_name='twopiecesuit',
            name='trouser_turn_up',
            field=models.CharField(choices=[('turn up', 'Turn up'), ("don't turn up", "Don't turn up")], max_length=100, null=True, verbose_name='Trouser Turn Up'),
        ),
    ]
