# Generated by Django 3.2.7 on 2021-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_auto_20211125_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='counts',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
