# Generated by Django 3.2.7 on 2021-11-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_alter_twopiecesuit_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='counts',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
