# Generated by Django 3.2.7 on 2021-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_alter_twopiecesuit_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
