# Generated by Django 3.2.7 on 2021-11-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_alter_twopiecesuit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='button_hole_thread',
            field=models.CharField(choices=[('match fabric', 'Match fabric'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True, verbose_name='Button Hole Thread'),
        ),
    ]
