# Generated by Django 3.2.7 on 2021-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_alter_twopiecesuit_button_hole_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='neck_felt_contrast',
            field=models.CharField(choices=[('no contrast fabric', 'No contrast fabric'), ('skye, black', 'Skye, black'), ('skye, brown', 'Skye, brown'), ('skye, electric blue', 'Skye, electric blue')], max_length=100, null=True, verbose_name='Neck Felt Contrast'),
        ),
    ]
