# Generated by Django 3.2.7 on 2021-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_alter_twopiecesuit_neck_felt_contrast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twopiecesuit',
            name='lining',
            field=models.CharField(choices=[('ardington, black', 'Ardington, black'), ('ardington, golden dark brown', 'Ardington, golden dark brown'), ('ardington, steel blue', 'Ardington, steel blue')], max_length=100, null=True),
        ),
    ]
