# Generated by Django 3.2.7 on 2021-12-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_twopiecesuit_instance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twopiecesuit',
            old_name='instance_type',
            new_name='type',
        ),
    ]
