# Generated by Django 3.2.7 on 2021-12-01 17:09

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_rename_instance_type_twopiecesuit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='threepiecesuit',
            name='button_hole_thread',
            field=models.CharField(choices=[('match fabric', 'Match fabric'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True, verbose_name='Button Hole Thread'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='buttoning',
            field=models.CharField(choices=[('one-button', 'One-button'), ('two-button', 'Two-button'), ('double-breasted', 'Double-breasted')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='buttons',
            field=models.CharField(choices=[('denver, black', 'Denver, black'), ('ridge, navy', 'Ridge, navy'), ('reggio, brown', 'Reggio, brown')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='counts',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='fabric',
            field=models.CharField(choices=[('havanna, black', 'Havanna, black'), ('stockholm, brown', 'Stockholm, brown')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='lapel',
            field=models.CharField(choices=[('standard lapel', 'Standard lapel'), ('slim lapel', 'Slim lapel'), ('peak lapel', 'Peak lapel'), ('shawl lapel', 'Shawl lapel')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='lapel_stitch',
            field=models.CharField(choices=[("don't stitch", "Don't stitch"), ('stitch lapel', 'Stitch lapel')], max_length=100, null=True, verbose_name='Lapel Sticth'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='lining',
            field=models.CharField(choices=[('ardington, black', 'Ardington, black'), ('ardington, golden dark brown', 'Ardington, golden dark brown'), ('ardington, steel blue', 'Ardington, steel blue')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='neck_felt_contrast',
            field=models.CharField(choices=[('no contrast fabric', 'No contrast fabric'), ('skye, black', 'Skye, black'), ('skye, brown', 'Skye, brown'), ('skye, electric blue', 'Skye, electric blue')], max_length=100, null=True, verbose_name='Neck Felt Contrast'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='pocket_flap',
            field=models.CharField(choices=[('make flap', 'Make flap'), ("don't make flap", "Don't make flap")], max_length=100, null=True, verbose_name='Pocket Flap'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=20),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='sleeve_buttons_contrast',
            field=models.CharField(choices=[('no sleeve button contrast', 'No sleeve button contrast'), ('denver, black', 'Denver, black'), ('ridge, navy', 'Ridge, navy'), ('reggio, brown', 'Reggio, brown')], max_length=100, null=True, verbose_name='Sleeve Buttons Contrast'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='sleeve_buttons_thread',
            field=models.CharField(choices=[('no sleeve button thread', 'No sleeve button thread'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True, verbose_name='Sleeve Buttons Thread'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='stitching_thread',
            field=models.CharField(choices=[('no stitching thread', 'No stitching thread'), ('white', 'White'), ('ivory', 'Ivory'), ('sand', 'Sand')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='ticket_pocket',
            field=models.CharField(choices=[('put ticket pocket', 'Put ticket pocket'), ("don't put ticket pocket", "Don't put ticket pocket")], max_length=100, null=True, verbose_name='Ticket Pocket'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='trouser_back_pocket_design',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('buttoned', 'Buttoned')], max_length=100, null=True, verbose_name='Trouser Back Pocket Design'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='trouser_back_pocket_placement',
            field=models.CharField(choices=[("don't place it", "Don't place it"), ('right', 'Right'), ('both', 'Both')], max_length=100, null=True, verbose_name='Trouser Back Pocket Placement'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='trouser_buttoning',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible')], max_length=100, null=True, verbose_name='Trouser Buttoning'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='trouser_pockets',
            field=models.CharField(choices=[('straight', 'Straight'), ('beveled', 'Beveled')], max_length=100, null=True, verbose_name='Trouser Pockets'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='trouser_turn_up',
            field=models.CharField(choices=[('turn up', 'Turn up'), ("don't turn up", "Don't turn up")], max_length=100, null=True, verbose_name='Trouser Turn Up'),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='type',
            field=models.CharField(default='two_piece_suit', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='threepiecesuit',
            name='vent',
            field=models.CharField(choices=[('single vent', 'Single vent'), ('double vent', 'Double vent')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='threepiecesuit',
            name='img',
            field=models.FileField(null=True, upload_to=index.models.upload_image_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='twopiecesuitsidebarelement',
            name='img',
            field=models.FileField(null=True, upload_to='two-piece-suit-sidebar-elements/', verbose_name='Picture'),
        ),
    ]
