# Generated by Django 3.2.7 on 2021-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_auto_20211201_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreePieceSuitSideBarElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('img', models.FileField(null=True, upload_to='three-piece-suit-sidebar-elements/', verbose_name='Picture')),
            ],
        ),
    ]
