# Generated by Django 3.2.7 on 2021-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_threepiecesuitsidebarelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threepiecesuit',
            name='type',
            field=models.CharField(default='three_piece_suit', editable=False, max_length=100),
        ),
    ]
